// This file was generated by TranslateSheet.
// Do NOT edit this file directly.
// Make changes in the TranslateSheet dashboard.

import { Translations } from "./translations.types";
  
  const ar: Translations = {
  features: {
    title1: "تعريف",
    description1: "حدد نص تطبيقك بالضبط حيث يُستخدم. يتيح لك TranslateSheet وضع الترجمات بجانب مكوناتك باستخدام كائنات بسيطة وآمنة من النوع. لا داعي للقفز بين الملفات أو تخمين وجود المفاتيح.",
    title2: "توليد",
    description2: "شغل أمر واحد فقط وسيقوم TranslateSheet بتوليد الترجمات تلقائيًا لكل مفتاح عبر مشروعك - حتى المفاتيح المتضمنة. استخدم ترجمات مدعومة بالذكاء الاصطناعي أو قم بدمج فريقك الخاص.",
    title3: "إدارة",
    description3: "إدارة جميع نصوص تطبيقك في مكان واحد باستخدام لوحة تحكم TranslateSheet. استأجر مترجمين، وقم بمراجعة التغييرات، وامتزج مباشرة بمستودعك باستخدام تكامل GitHub.",
  },
  ResponsiveHeading: {
    translateSheetHelpsYou: "TranslateSheet يساعدك",
    define: "تعريف",
    generate: "توليد",
    manage: "إدارة",
    simpleAPI: "الترجمات بواجهة برمجية بسيطة",
    ctaButtonLabel: "تعرف على الجديد!",
    subHeading: "قم ببناء تطبيقات متعددة اللغات باستخدام React و React Native. قم بتوحيد إنشاء ملفات الترجمة وتبسيط التوطين منذ اليوم الأول.",
    getStarted: "ابدأ الآن",
    readTheDocs: "اقرأ الوثائق",
  },
  BasicNavbar: {
    dashboard: "لوحة القيادة",
    docs: "المستندات",
  },
  Banner: {
    heading: "TranslateSheet الآن في البيتا",
  },
  IDEExamples: {
    heading: "جربها!",
    subHeading: "مع ملف تكوين واحد، أنت على استعداد لبدء استخدام TranslateSheet في مشروعك!",
  },
  PricingTiers: {
    hobby: {
      title: "هواية",
      price: "مجاني",
      description: "للمبتدئين وهواة الذين يرغبون في تجربتها.",
      features: {
        projects: "مشروع واحد",
        members: "مقعد عضو في مشروع واحد",
        keys: "250 مفتاح مترجم مستضاف",
        languages: "لغتين مترجمتين",
        support: "الدعم عبر البريد الإلكتروني",
      },
      buttonText: "متابعة مجانًا",
    },
    professional: {
      title: "احترافي",
      price: "9 دولارات شهريًا",
      description: "للفرق الصغيرة التي لديها أقل من 10 أعضاء.",
      features: {
        projects: "10 مشاريع",
        members: "مقاعد غير محدودة لأعضاء المشروع",
        keys: "مفاتيح مترجمة مستضافة غير محدودة",
        languages: "لغات مترجمة غير محدودة",
        support: "الوصول إلى مركز المساعدة",
      },
      buttonText: "ابدأ الآن",
    },
  },
  PricingPlans: {
    heading: "تسعير بسيط، مصمم للتطور",
    subHeading: "لا توجد رسوم مفاجئة أو عقود. ابدأ مجانًا، وقم بالتوسع عند الحاجة.",
    currentPlan: "الخطة الحالية",
    openSourceDev: "هل أنت مطور مفتوح المصدر؟",
    discount: "احصل على خصم",
  },
};
export default ar;