// This file was generated by TranslateSheet.
// Do NOT edit this file directly.
// Make changes in the TranslateSheet dashboard.

import { Translations } from "./translations.types";
  
  const ar: Translations = {
  ResponsiveHeading: {
    translateSheetHelpsYou: "يساعدك TranslateSheet",
    define: "تعريف",
    generate: "يولد",
    manage: "يدير",
    simpleAPI: "الترجمات باستخدام واجهة برمجة التطبيقات البسيطة",
    ctaButtonLabel: "تعلم ما الجديد!",
    subHeading: "قم ببناء تطبيقات متعددة اللغات باستخدام React وReact Native. قم بتوليد ملفات الترجمة تلقائيًا وبسهولة عند توطين التطبيق اعتبارًا من اليوم الأول.",
    getStarted: "ابدأ",
    readTheDocs: "اقرأ الوثائق",
  },
  BasicNavbar: {
    dashboard: "لوحة القيادة",
    docs: "الوثائق",
  },
  Banner: {
    heading: "TranslateSheet الآن في البيتا",
  },
  IDEExamples: {
    heading: "جربها!",
    subHeading: "مع ملف تكوين واحد، أنت على استعداد لبدء استخدام TranslateSheet في مشروعك!",
  },
  PricingTiers: {
    hobby: {
      title: "هواية",
      price: "مجانًا",
      description: "للمبتدئين وهواة الذين يرغبون في التجربة.",
      features: {
        projects: "مشروع واحد",
        members: "مقعد عضو في مشروع واحد",
        keys: "250 مفتاح مترجم مستضاف",
        languages: "لغتين مترجمتين",
        support: "دعم بريد إلكتروني",
      },
      buttonText: "تابع مع المجاني",
    },
    professional: {
      title: "احترافي",
      price: "9 دولار شهريًا",
      description: "للفرق الصغيرة التي تحتوي على أقل من 10 أعضاء.",
      features: {
        projects: "10 مشاريع",
        members: "مقاعد غير محدودة لأعضاء المشروع",
        keys: "مفاتيح مترجمة مستضافة غير محدودة",
        languages: "لغات مترجمة غير محدودة",
        support: "وصول إلى مركز المساعدة",
      },
      buttonText: "ابدأ الآن",
    },
  },
  PricingPlans: {
    heading: "missing",
    currentPlan: "الخطة الحالية",
    openSourceDev: "هل أنت مطور مفتوح المصدر؟",
    discount: "احصل على خصم",
  },
};
export default ar;