// This file was generated by TranslateSheet.
// Do NOT edit this file directly.
// Make changes in the TranslateSheet dashboard.

const ar: Record<string, any> = {
  ResponsiveHeading: {
    translateSheetHelpsYou: "يساعدك TranslateSheet",
    define: "تعريف",
    generate: "توليد",
    manage: "إدارة",
    simpleAPI: "الترجمات بواسطة واجهة برمجة التطبيقات البسيطة",
    ctaButtonLabel: "تعرف على الجديد!",
    subHeading: "قم ببناء تطبيقات متعددة اللغات باستخدام React و React Native. أتمت توليد ملفات الترجمة وبسهولة تامة منذ اليوم الأول.",
    getStarted: "ابدأ الآن",
    readTheDocs: "اقرأ الوثائق",
  },
  BasicNavbar: {
    dashboard: "لوحة القيادة",
    docs: "الوثائق",
  },
  Banner: {
    heading: "TranslateSheet الآن في البيتا",
  },
};
export default ar;