// This file was generated by TranslateSheet.
// Do NOT edit this file directly.
// To change primary language strings, update your TranslateSheet object declarations.

const en: Record<string, any> = {
  ResponsiveHeading: {
    translateSheetHelpsYou: "TranslateSheet helps you",
    define: "define",
    generate: "generate",
    manage: "manage",
    simpleAPI: "translations with a simple API",
    ctaButtonLabel: "Learn what's new!",
    subHeading: "Build multilingual apps with React and React Native. Automate translation file generation and simplify localization from day one.",
    getStarted: "Get Started",
    readTheDocs: "Read the Docs",
  },
  BasicNavbar: {
    dashboard: "Dashboard",
    docs: "Docs",
  },
  Banner: {
    heading: "TranslateSheet now in beta",
  },
};
export default en;