// This file was generated by TranslateSheet.
// Do NOT edit this file directly.
// Make changes in the TranslateSheet dashboard.

import { Translations } from "./translations.types";
  
  const es: Translations = {
  ResponsiveHeading: {
    translateSheetHelpsYou: "TranslateSheet te ayuda",
    define: "definir",
    generate: "generar",
    manage: "administrar",
    simpleAPI: "traducciones con una API simple",
    ctaButtonLabel: "¡Descubre las novedades!",
    subHeading: "Construye aplicaciones multilingües con React y React Native. Automatiza la generación de archivos de traducción y simplifica la localización desde el primer día.",
    getStarted: "Empezar",
    readTheDocs: "Leer la documentación",
  },
  BasicNavbar: {
    dashboard: "Tablero",
    docs: "Documentos",
  },
  Banner: {
    heading: "TranslateSheet ahora en beta",
  },
  IDEExamples: {
    heading: "¡Pruébalo!",
    subHeading: "¡Con un solo archivo de configuración, estás listo para empezar a usar TranslateSheet en tu proyecto!",
  },
  PricingTiers: {
    hobby: {
      title: "Hobby",
      price: "Gratis",
      description: "Para principiantes y aficionados que quieran probar.",
      features: {
        projects: "1 proyecto",
        members: "1 asiento de miembro del proyecto",
        keys: "250 claves traducidas alojadas",
        languages: "2 idiomas traducidos",
        support: "Soporte por correo electrónico",
      },
      buttonText: "Continuar con Gratis",
    },
    professional: {
      title: "Profesional",
      price: "$9 al mes",
      description: "Para equipos pequeños que tienen menos de 10 miembros.",
      features: {
        projects: "10 proyectos",
        members: "Asientos de miembro del proyecto ilimitados",
        keys: "Claves traducidas alojadas ilimitadas",
        languages: "Idiomas traducidos ilimitados",
        support: "Acceso al centro de ayuda",
      },
      buttonText: "Empezar",
    },
  },
  PricingPlans: {
    heading: "Sin sorpresas en tarifas ni contratos. Empieza gratis y escala cuando lo necesites.",
    currentPlan: "Plan actual",
    openSourceDev: "¿Eres un desarrollador de código abierto?",
    discount: "Obtén un descuento",
  },
};
export default es;