// This file was generated by TranslateSheet.
// Do NOT edit this file directly.
// Make changes in the TranslateSheet dashboard.

const es: Record<string, any> = {
  ResponsiveHeading: {
    translateSheetHelpsYou: "TranslateSheet te ayuda",
    define: "definir",
    generate: "generar",
    manage: "administrar",
    simpleAPI: "traducciones con una API simple",
    ctaButtonLabel: "¡Descubre las novedades!",
    subHeading: "Construye aplicaciones multilingües con React y React Native. Automatiza la generación de archivos de traducción y simplifica la localización desde el primer día.",
    getStarted: "Empezar",
    readTheDocs: "Leer la documentación",
  },
  BasicNavbar: {
    dashboard: "Tablero",
    docs: "Documentos",
  },
  Banner: {
    heading: "TranslateSheet ahora en beta",
  },
};
export default es;