// This file was generated by TranslateSheet.
// Do NOT edit this file directly.
// Make changes in the TranslateSheet dashboard.

import { Translations } from "./translations.types";
  
  const ja: Translations = {
  ResponsiveHeading: {
    translateSheetHelpsYou: "TranslateSheet helps you",
    define: "定義する",
    generate: "生成する",
    manage: "管理する",
    simpleAPI: "シンプルなAPIを使用して翻訳する",
    ctaButtonLabel: "新着情報を学ぶ！",
    subHeading: "ReactとReact Nativeで多言語アプリを構築します。翻訳ファイルの生成を自動化し、初日からローカライズを簡素化します。",
    getStarted: "はじめる",
    readTheDocs: "ドキュメントを読む",
  },
  BasicNavbar: {
    dashboard: "ダッシュボード",
    docs: "ドキュメント",
  },
  Banner: {
    heading: "TranslateSheetは現在ベータ版です",
  },
  IDEExamples: {
    heading: "試してみてください！",
    subHeading: "単一の設定ファイルで、プロジェクトでTranslateSheetを使用する準備が整います！",
  },
  PricingTiers: {
    hobby: {
      title: "趣味",
      price: "無料",
      description: "始めてみたい初心者や趣味のある人向け",
      features: {
        projects: "1つのプロジェクト",
        members: "1つのプロジェクトメンバーシート",
        keys: "250のホストされた翻訳キー",
        languages: "2つの翻訳言語",
        support: "メールサポート",
      },
      buttonText: "無料で続行",
    },
    professional: {
      title: "プロフェッショナル",
      price: "月額$9",
      description: "10人未満の小さなチーム向け",
      features: {
        projects: "10のプロジェクト",
        members: "無制限のプロジェクトメンバーシート",
        keys: "無制限のホストされた翻訳キー",
        languages: "無制限の翻訳言語",
        support: "ヘルプセンターアクセス",
      },
      buttonText: "開始する",
    },
  },
  PricingPlans: {
    heading: "予期せぬ料金や契約はありません。無料で開始し、必要に応じてスケールしてください。",
    currentPlan: "現在のプラン",
    openSourceDev: "オープンソース開発者ですか？",
    discount: "割引を受ける",
  },
};
export default ja;