// This file was generated by TranslateSheet.
// Do NOT edit this file directly.
// Make changes in the TranslateSheet dashboard.

const ja: Record<string, any> = {
  ResponsiveHeading: {
    translateSheetHelpsYou: "TranslateSheetはあなたを助けます",
    define: "定義する",
    generate: "生成する",
    manage: "管理する",
    simpleAPI: "シンプルなAPIで翻訳",
    ctaButtonLabel: "新着情報を学ぶ！",
    subHeading: "ReactとReact Nativeで多言語アプリを構築します。翻訳ファイルの自動生成を行い、最初からローカライゼーションを簡素化します。",
    getStarted: "開始する",
    readTheDocs: "ドキュメントを読む",
  },
  BasicNavbar: {
    dashboard: "ダッシュボード",
    docs: "ドキュメント",
  },
  Banner: {
    heading: "TranslateSheetは今ベータ版です",
  },
};
export default ja;