// This file was generated by TranslateSheet.
// Do NOT edit this file directly.
// Make changes in the TranslateSheet dashboard.

const pt: Record<string, any> = {
  ResponsiveHeading: {
    translateSheetHelpsYou: "TranslateSheet ajuda você",
    define: "definir",
    generate: "gerar",
    manage: "gerenciar",
    simpleAPI: "traduções com uma API simples",
    ctaButtonLabel: "Saiba o que há de novo!",
    subHeading: "Construa aplicativos multilíngues com React e React Native. Automatize a geração de arquivos de tradução e simplifique a localização desde o primeiro dia.",
    getStarted: "Começar",
    readTheDocs: "Leia a documentação",
  },
  BasicNavbar: {
    dashboard: "Painel",
    docs: "Documentos",
  },
  Banner: {
    heading: "TranslateSheet agora em beta",
  },
};
export default pt;