// This file was generated by TranslateSheet.
// Do NOT edit this file directly.
// Make changes in the TranslateSheet dashboard.

import { Translations } from "./translations.types";
  
  const pt: Translations = {
  ResponsiveHeading: {
    translateSheetHelpsYou: "TranslateSheet ajuda você",
    define: "definir",
    generate: "gerar",
    manage: "gerenciar",
    simpleAPI: "traduções com uma API simples",
    ctaButtonLabel: "Saiba o que há de novo!",
    subHeading: "Construa aplicativos multilíngues com React e React Native. Automatize a geração de arquivos de tradução e simplifique a localização desde o início.",
    getStarted: "Começar",
    readTheDocs: "Leia a documentação",
  },
  BasicNavbar: {
    dashboard: "Painel",
    docs: "Documentos",
  },
  Banner: {
    heading: "TranslateSheet agora em beta",
  },
  IDEExamples: {
    heading: "Experimente!",
    subHeading: "Com um único arquivo de configuração, você está pronto para começar a usar o TranslateSheet em seu projeto!",
  },
  PricingTiers: {
    hobby: {
      title: "Hobby",
      price: "Grátis",
      description: "Para iniciantes e entusiastas que querem experimentar.",
      features: {
        projects: "1 projeto",
        members: "1 assento de membro do projeto",
        keys: "250 chaves traduzidas hospedadas",
        languages: "2 idiomas traduzidos",
        support: "Suporte por e-mail",
      },
      buttonText: "Continuar com Grátis",
    },
    professional: {
      title: "Profissional",
      price: "$9 por mês",
      description: "Para pequenas equipes com menos de 10 membros.",
      features: {
        projects: "10 projetos",
        members: "Assentos ilimitados de membros do projeto",
        keys: "Chaves traduzidas hospedadas ilimitadas",
        languages: "Idiomas traduzidos ilimitados",
        support: "Acesso ao centro de ajuda",
      },
      buttonText: "Começar",
    },
  },
  PricingPlans: {
    heading: "Sem surpresas com taxas ou contratos. Comece de graça e aumente quando precisar.",
    currentPlan: "Plano atual",
    openSourceDev: "Você é um desenvolvedor de código aberto?",
    discount: "Obtenha um desconto",
  },
};
export default pt;