// This file was generated by TranslateSheet.
// Do NOT edit this file directly.
// Make changes in the TranslateSheet dashboard.

const ru: Record<string, any> = {
  ResponsiveHeading: {
    translateSheetHelpsYou: "TranslateSheet помогает вам",
    define: "определить",
    generate: "генерировать",
    manage: "управлять",
    simpleAPI: "переводы с помощью простого API",
    ctaButtonLabel: "Узнайте, что нового!",
    subHeading: "Создавайте многоязычные приложения с помощью React и React Native. Автоматизируйте создание файлов перевода и упростите локализацию с первого дня.",
    getStarted: "Начать",
    readTheDocs: "Прочитать документацию",
  },
  BasicNavbar: {
    dashboard: "Панель управления",
    docs: "Документация",
  },
  Banner: {
    heading: "TranslateSheet теперь в бета-версии",
  },
};
export default ru;