// This file was generated by TranslateSheet.
// Do NOT edit this file directly.
// Make changes in the TranslateSheet dashboard.

import { Translations } from "./translations.types";
  
  const ru: Translations = {
  ResponsiveHeading: {
    translateSheetHelpsYou: "TranslateSheet помогает вам",
    define: "определить",
    generate: "создать",
    manage: "управлять",
    simpleAPI: "переводы с простым API",
    ctaButtonLabel: "Узнайте, что нового!",
    subHeading: "Создавайте многоязычные приложения с React и React Native. Автоматизируйте генерацию файлов перевода и упростите локализацию с первого дня.",
    getStarted: "Начать",
    readTheDocs: "Прочитать документацию",
  },
  BasicNavbar: {
    dashboard: "Панель управления",
    docs: "Документация",
  },
  Banner: {
    heading: "TranslateSheet теперь в бета-версии",
  },
  IDEExamples: {
    heading: "Попробуйте!",
    subHeading: "С одним файлом конфигурации вы готовы начать использовать TranslateSheet в своем проекте!",
  },
  PricingTiers: {
    hobby: {
      title: "Хобби",
      price: "Бесплатно",
      description: "Для начинающих и любителей, которые хотят попробовать.",
      features: {
        projects: "1 проект",
        members: "1 место для участника проекта",
        keys: "250 размещенных переведенных ключей",
        languages: "2 переведенных языка",
        support: "Поддержка по электронной почте",
      },
      buttonText: "Продолжить бесплатно",
    },
    professional: {
      title: "Профессиональный",
      price: "$9 в месяц",
      description: "Для малых команд, в которых менее 10 участников.",
      features: {
        projects: "10 проектов",
        members: "Неограниченное количество мест для участников проекта",
        keys: "Неограниченное количество размещенных переведенных ключей",
        languages: "Неограниченное количество переведенных языков",
        support: "Доступ в центр поддержки",
      },
      buttonText: "Начать",
    },
  },
  PricingPlans: {
    heading: "Нет сюрпризов в оплатах или контрактах. Начните бесплатно и масштабируйтесь по мере необходимости.",
    currentPlan: "Текущий план",
    openSourceDev: "Вы разработчик открытого исходного кода?",
    discount: "Получите скидку",
  },
};
export default ru;