// This file was generated by TranslateSheet.
// Do NOT edit this file directly.
// Run translate-sheet generate-types to regenerate this file.

export type Translations = {
  ResponsiveHeading: {
    translateSheetHelpsYou: string;
    define: string;
    generate: string;
    manage: string;
    simpleAPI: string;
    ctaButtonLabel: string;
    subHeading: string;
    getStarted: string;
    readTheDocs: string;
  };
  BasicNavbar: {
    dashboard: string;
    docs: string;
  };
  Banner: {
    heading: string;
  };
  IDEExamples: {
    heading: string;
    subHeading: string;
  };
  PricingTiers: {
    hobby: {
      title: string;
      price: string;
      description: string;
      features: {
        projects: string;
        members: string;
        keys: string;
        languages: string;
        support: string;
      };
      buttonText: string;
    };
    professional: {
      title: string;
      price: string;
      description: string;
      features: {
        projects: string;
        members: string;
        keys: string;
        languages: string;
        support: string;
      };
      buttonText: string;
    };
  };
  PricingPlans: {
    heading: string;
    currentPlan: string;
    openSourceDev: string;
    discount: string;
  };
};
