// This file was generated by TranslateSheet.
// Do NOT edit this file directly.
// Make changes in the TranslateSheet dashboard.

import { Translations } from "./translations.types";
  
  const zh: Translations = {
  ResponsiveHeading: {
    translateSheetHelpsYou: "TranslateSheet 帮助您",
    define: "定义",
    generate: "生成",
    manage: "管理",
    simpleAPI: "使用简单的 API 进行翻译",
    ctaButtonLabel: "了解新内容！",
    subHeading: "使用 React 和 React Native 构建多语言应用。自动化翻译文件生成，简化从第一天开始的本地化。",
    getStarted: "开始",
    readTheDocs: "阅读文档",
  },
  BasicNavbar: {
    dashboard: "仪表板",
    docs: "文档",
  },
  Banner: {
    heading: "TranslateSheet 现在处于测试阶段",
  },
  IDEExamples: {
    heading: "试一试吧！",
    subHeading: "只需一个配置文件，您就可以开始在项目中使用 TranslateSheet 了！",
  },
  PricingTiers: {
    hobby: {
      title: "业余爱好",
      price: "免费",
      description: "适用于想要尝试的初学者和业余爱好者。",
      features: {
        projects: "1 个项目",
        members: "1 个项目成员席位",
        keys: "250 个托管的翻译键",
        languages: "2 种翻译语言",
        support: "电子邮件支持",
      },
      buttonText: "继续免费使用",
    },
    professional: {
      title: "专业版",
      price: "$9 每月",
      description: "适用于拥有不到 10 名成员的小团队。",
      features: {
        projects: "10 个项目",
        members: "无限项目成员席位",
        keys: "无限托管的翻译键",
        languages: "无限翻译语言",
        support: "访问帮助中心",
      },
      buttonText: "开始使用",
    },
  },
  PricingPlans: {
    heading: "没有隐藏费用或合同。免费开始，根据需要扩展。",
    currentPlan: "当前计划",
    openSourceDev: "您是开源开发者吗？",
    discount: "获得折扣",
  },
};
export default zh;