// This file was generated by TranslateSheet.
// Do NOT edit this file directly.
// Make changes in the TranslateSheet dashboard.

const zh: Record<string, any> = {
  ResponsiveHeading: {
    translateSheetHelpsYou: "TranslateSheet 帮助您",
    define: "定义",
    generate: "生成",
    manage: "管理",
    simpleAPI: "使用简单的 API 进行翻译",
    ctaButtonLabel: "了解新功能！",
    subHeading: "使用 React 和 React Native 构建多语言应用。自动化翻译文件生成，从一开始就简化本地化。",
    getStarted: "开始",
    readTheDocs: "阅读文档",
  },
  BasicNavbar: {
    dashboard: "仪表板",
    docs: "文档",
  },
  Banner: {
    heading: "TranslateSheet 现已推出测试版",
  },
};
export default zh;